# -*- coding: utf-8 -*-
"""Gradient_Descent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3DTuTjPvRe3qs5TcSYxFbtEA-767g6X
"""
from BatchGradientDescent import BatchGradientDescent


train_x = [[1,2,3,4,5,6]]
train_y = [10*value + 1 for value in train_x[0]]

model = BatchGradientDescent(train_x,train_y,epochs=1000)
print(model)

model.train_the_model(False)

model.parameters

value = model.estimate_value(20)
print("Estimated gradient value :",value)

model.find_optimal_parameters()
model.parameters

value = model.estimate_value(5)
print("Estimated normal equation value : ",value)